#!/bin/bash
set -eo pipefail

ghtoken=$1;

mkdir -p ~/.gem && echo ":github: Bearer $ghtoken" >> ~/.gem/credentials
chmod 0600 /root/.gem/credentials

gemversion=$(cat lib/contrib/auth/version.rb | grep -o '[0-9]\{1,\}\.[0-9]\{1,\}.[0-9]\{1,\}')

echo $ghtoken
echo $gemversion

gem build contrib-auth.gemspec
gem push --key github --host https://rubygems.pkg.github.com/contribyard contrib-auth-$gemversion.gem
